import type { Linter } from 'eslint';

const core: Linter.Config = {
	name: '@biffud/eslint-config/core',
	rules: {
		'accessor-pairs': 'error',
		'array-callback-return': ['error', { checkForEach: true }],
		'arrow-body-style': [
			'error',
			'as-needed',
			{ requireReturnForObjectLiteral: false },
		],
		complexity: ['error', { variant: 'modified', max: 10 }],
		'consistent-this': 'error',
		'constructor-super': 'error',
		curly: 'error',
		'default-case-last': 'error',
		eqeqeq: ['error', 'always', { null: 'always' }],
		'for-direction': 'error',
		'grouped-accessor-pairs': ['error', 'getBeforeSet'],
		'guard-for-in': 'error',
		'logical-assignment-operators': [
			'error',
			'always',
			{ enforceForIfStatements: true },
		],
		'max-depth': ['error', { max: 5 }],
		'max-lines': [
			'error',
			{ max: 450, skipBlankLines: true, skipComments: true },
		],
		'max-nested-callbacks': ['error', { max: 3 }],
		'new-cap': ['error', { capIsNew: false }],
		'no-alert': 'error',
		'no-async-promise-executor': 'error',
		'no-await-in-loop': 'error',
		'no-caller': 'error',
		'no-case-declarations': 'error',
		'no-class-assign': 'error',
		'no-compare-neg-zero': 'error',
		'no-cond-assign': 'error',
		'no-console': 'error',
		'no-const-assign': 'error',
		'no-constant-binary-expression': 'error',
		'no-constant-condition': ['error', { checkLoops: false }],
		'no-constructor-return': 'error',
		'no-control-regex': 'error',
		'no-debugger': 'error',
		'no-delete-var': 'error',
		'no-dupe-args': 'error',
		'no-dupe-else-if': 'error',
		'no-dupe-keys': 'error',
		'no-duplicate-case': 'error',
		'no-empty': 'error',
		'no-empty-character-class': 'error',
		'no-empty-pattern': 'error',
		'no-empty-static-block': 'error',
		'no-eval': 'error',
		'no-ex-assign': 'error',
		'no-extend-native': 'error',
		'no-extra-bind': 'error',
		'no-extra-boolean-cast': 'error',
		'no-fallthrough': 'error',
		'no-func-assign': 'error',
		'no-import-assign': 'error',
		'no-invalid-regexp': 'error',
		'no-irregular-whitespace': 'error',
		'no-iterator': 'error',
		'no-labels': 'error',
		'no-lone-blocks': 'error',
		'no-lonely-if': 'error',
		'no-loop-func': 'error',
		'no-loss-of-precision': 'error',
		'no-misleading-character-class': 'error',
		'no-multi-assign': 'error',
		'no-multi-str': 'error',
		'no-negated-condition': 'error',
		'no-new': 'error',
		'no-new-func': 'error',
		'no-new-native-nonconstructor': 'error',
		'no-new-wrappers': 'error',
		'no-nonoctal-decimal-escape': 'error',
		'no-obj-calls': 'error',
		'no-object-constructor': 'error',
		'no-octal': 'error',
		'no-octal-escape': 'error',
		'no-param-reassign': ['error', { props: true }],
		'no-plusplus': 'error',
		'no-promise-executor-return': 'error',
		'no-proto': 'error',
		'no-prototype-builtins': 'error',
		'no-regex-spaces': 'error',
		'no-return-assign': ['error', 'always'],
		'no-script-url': 'error',
		'no-self-assign': 'error',
		'no-self-compare': 'error',
		'no-sequences': 'error',
		'no-shadow-restricted-names': 'error',
		'no-sparse-arrays': 'error',
		'no-template-curly-in-string': 'error',
		'no-this-before-super': 'error',
		'no-unexpected-multiline': 'error',
		'no-unmodified-loop-condition': 'error',
		'no-unneeded-ternary': ['error', { defaultAssignment: false }],
		'no-unreachable': 'error',
		'no-unreachable-loop': 'error',
		'no-unsafe-finally': 'error',
		'no-unsafe-negation': 'error',
		'no-useless-assignment': 'error',
		'no-useless-backreference': 'error',
		'no-useless-call': 'error',
		'no-useless-catch': 'error',
		'no-useless-computed-key': 'error',
		'no-useless-concat': 'error',
		'no-useless-escape': 'error',
		'no-useless-rename': 'error',
		'no-useless-return': 'error',
		'no-var': 'error',
		'no-void': ['error', { allowAsStatement: true }],
		'no-with': 'error',
		'object-shorthand': 'error',
		'one-var': ['error', { initialized: 'never' }],
		'operator-assignment': 'error',
		'prefer-arrow-callback': ['error', { allowUnboundThis: false }],
		'prefer-const': 'error',
		'prefer-exponentiation-operator': 'error',
		'prefer-named-capture-group': 'error',
		'prefer-numeric-literals': 'error',
		'prefer-object-has-own': 'error',
		'prefer-object-spread': 'error',
		'prefer-regex-literals': ['error', { disallowRedundantWrapping: true }],
		'prefer-rest-params': 'error',
		'prefer-spread': 'error',
		'prefer-template': 'error',
		'preserve-caught-error': ['error', { requireCatchParameter: true }],
		radix: ['error', 'always'],
		'require-atomic-updates': 'error',
		'require-unicode-regexp': ['error', { requireFlag: 'v' }],
		'require-yield': 'error',
		strict: 'error',
		'symbol-description': 'error',
		'unicode-bom': 'error',
		'use-isnan': ['error', { enforceForIndexOf: true }],
		'valid-typeof': ['error', { requireStringLiterals: true }],
		yoda: 'error',
	},
};

export { core };
