import type { Linter } from 'eslint';

const core: Linter.Config = {
	name: '@biffud/eslint-config/core',
	rules: {
		'array-callback-return': [
			'error',
			{ allowImplicit: false, allowVoid: false, checkForEach: true },
		],
		'consistent-this': ['error', 'that'],
		'constructor-super': 'error',
		'default-case-last': 'error',
		eqeqeq: ['error', 'always', { null: 'always' }],
		'for-direction': 'error',
		'guard-for-in': 'error',
		'logical-assignment-operators': [
			'error',
			'always',
			{ enforceForIfStatements: true },
		],
		'no-alert': 'error',
		'no-async-promise-executor': 'error',
		'no-await-in-loop': 'error',
		'no-caller': 'error',
		'no-case-declarations': 'error',
		'no-class-assign': 'error',
		'no-compare-neg-zero': 'error',
		'no-cond-assign': 'error',
		'no-console': 'error',
		'no-const-assign': 'error',
		'no-constant-binary-expression': 'error',
		'no-constructor-return': 'error',
		'no-control-regex': 'error',
		'no-debugger': 'error',
		'no-dupe-else-if': 'error',
		'no-dupe-keys': 'error',
		'no-duplicate-case': 'error',
		'no-empty': ['error', { allowEmptyCatch: false }],
		'no-empty-character-class': 'error',
		'no-empty-pattern': 'error',
		'no-empty-static-block': 'error',
		'no-eval': 'error',
		'no-ex-assign': 'error',
		'no-extend-native': 'error',
		'no-extra-bind': 'error',
		'no-extra-boolean-cast': 'error',
		'no-fallthrough': 'error',
		'no-func-assign': 'error',
		'no-invalid-regexp': 'error',
		'no-iterator': 'error',
		'no-labels': ['error', { allowLoop: false, allowSwitch: false }],
		'no-lone-blocks': 'error',
		'no-lonely-if': 'error',
		'no-loop-func': 'error',
		'no-loss-of-precision': 'error',
		'no-multi-assign': ['error', { ignoreNonDeclaration: false }],
		'no-negated-condition': 'error',
		'no-new': 'error',
		'no-new-func': 'error',
		'no-new-native-nonconstructor': 'error',
		'no-new-wrappers': 'error',
		'no-obj-calls': 'error',
		'no-object-constructor': 'error',
		'no-param-reassign': ['error', { props: true }],
		'no-plusplus': 'error',
		'no-proto': 'error',
		'no-prototype-builtins': 'error',
		'no-regex-spaces': 'error',
		'no-return-assign': ['error', 'always'],
		'no-script-url': 'error',
		'no-self-assign': ['error', { props: true }],
		'no-self-compare': 'error',
		'no-sequences': 'error',
		'no-shadow-restricted-names': 'error',
		'no-sparse-arrays': 'error',
		'no-template-curly-in-string': 'error',
		'no-this-before-super': 'error',
		'no-unmodified-loop-condition': 'error',
		'no-unneeded-ternary': ['error', { defaultAssignment: false }],
		'no-unreachable': 'error',
		'no-unreachable-loop': 'error',
		'no-unsafe-finally': 'error',
		'no-unsafe-negation': 'error',
		'no-useless-backreference': 'error',
		'no-useless-call': 'error',
		'no-useless-catch': 'error',
		'no-useless-computed-key': 'error',
		'no-useless-concat': 'error',
		'no-useless-escape': 'error',
		'no-useless-rename': 'error',
		'no-useless-return': 'error',
		'no-var': 'error',
		'no-void': ['error', { allowAsStatement: true }],
		'object-shorthand': ['error', 'always'],
		'one-var': ['error', { initialized: 'never' }],
		'operator-assignment': ['error', 'always'],
		'prefer-arrow-callback': [
			'error',
			{ allowNamedFunctions: false, allowUnboundThis: false },
		],
		'prefer-exponentiation-operator': 'error',
		'prefer-named-capture-group': 'error',
		'prefer-numeric-literals': 'error',
		'prefer-object-has-own': 'error',
		'prefer-object-spread': 'error',
		'prefer-rest-params': 'error',
		'prefer-spread': 'error',
		'prefer-template': 'error',
		radix: ['error', 'always'],
		'require-yield': 'error',
		'symbol-description': 'error',
		'use-isnan': [
			'error',
			{ enforceForSwitchCase: true, enforceForIndexOf: true },
		],
		'valid-typeof': ['error', { requireStringLiterals: true }],
		yoda: ['error', 'never'],
	},
};

export { core };
