import type { Linter } from 'eslint';

const core: Linter.Config = {
	name: '@biffud/eslint-config/core',
	rules: {
		'constructor-super': 'error',
		'default-case-last': 'error',
		'for-direction': 'error',
		'guard-for-in': 'error',
		'no-alert': 'error',
		'no-async-promise-executor': 'error',
		'no-await-in-loop': 'error',
		'no-case-declarations': 'error',
		'no-class-assign': 'error',
		'no-compare-neg-zero': 'error',
		'no-cond-assign': 'error',
		'no-console': 'error',
		'no-const-assign': 'error',
		'no-constructor-return': 'error',
		'no-control-regex': 'error',
		'no-debugger': 'error',
		'no-dupe-else-if': 'error',
		'no-dupe-keys': 'error',
		'no-duplicate-case': 'error',
		'no-empty-character-class': 'error',
		'no-empty-pattern': 'error',
		'no-empty-static-block': 'error',
		'no-eval': 'error',
		'no-ex-assign': 'error',
		'no-extend-native': 'error',
		'no-extra-bind': 'error',
		'no-extra-boolean-cast': 'error',
		'no-fallthrough': 'error',
		'no-func-assign': 'error',
		'no-invalid-regexp': 'error',
		'no-iterator': 'error',
		'no-lone-blocks': 'error',
		'no-lonely-if': 'error',
		'no-loss-of-precision': 'error',
		'no-negated-condition': 'error',
		'no-new': 'error',
		'no-new-func': 'error',
		'no-new-native-nonconstructor': 'error',
		'no-new-wrappers': 'error',
		'no-object-constructor': 'error',
		'no-plusplus': 'error',
		'no-proto': 'error',
		'no-prototype-builtins': 'error',
		'no-regex-spaces': 'error',
		'no-script-url': 'error',
		'no-self-compare': 'error',
		'no-sequences': 'error',
		'no-sparse-arrays': 'error',
		'no-template-curly-in-string': 'error',
		'no-this-before-super': 'error',
		'no-unreachable': 'error',
		yoda: ['error', 'never'],
	},
};

export { core };
